spring:
  application:
    name: BudgetBuddy
  datasource:
    url: jdbc:postgresql://localhost:5432/budgetBuddyDB
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml