-- liquibase formatted sql

-- changeset ldf:1720984979297-1
CREATE TABLE bank_account
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_number VARCHAR(255)                            NOT NULL,
    balance        DECIMAL                                 NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_bank_account PRIMARY KEY (id)
);

-- changeset ldf:1720984979297-2
CREATE TABLE budgets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    amount     DECIMAL                                 NOT NULL,
    start_date date                                    NOT NULL,
    end_date   date                                    NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_budgets PRIMARY KEY (id)
);

-- changeset ldf:1720984979297-3
CREATE TABLE financial_goals
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    target_amount DECIMAL                                 NOT NULL,
    start_date    date                                    NOT NULL,
    end_date      date                                    NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_financial_goals PRIMARY KEY (id)
);

-- changeset ldf:1720984979297-4
CREATE TABLE transaction_categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    type VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_transaction_categories PRIMARY KEY (id)
);

-- changeset ldf:1720984979297-5
CREATE TABLE transactions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount           DECIMAL                                 NOT NULL,
    transaction_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description      VARCHAR(255)                            NOT NULL,
    bank_account_id  BIGINT                                  NOT NULL,
    category_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

-- changeset ldf:1720984979297-6
CREATE TABLE users
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

-- changeset ldf:1720984979297-7
ALTER TABLE bank_account
    ADD CONSTRAINT uc_bank_account_account_number UNIQUE (account_number);

-- changeset ldf:1720984979297-8
ALTER TABLE transaction_categories
    ADD CONSTRAINT uc_transaction_categories_name UNIQUE (name);

-- changeset ldf:1720984979297-9
ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

-- changeset ldf:1720984979297-10
ALTER TABLE bank_account
    ADD CONSTRAINT FK_BANK_ACCOUNT_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- changeset ldf:1720984979297-11
ALTER TABLE budgets
    ADD CONSTRAINT FK_BUDGETS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- changeset ldf:1720984979297-12
ALTER TABLE financial_goals
    ADD CONSTRAINT FK_FINANCIAL_GOALS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- changeset ldf:1720984979297-13
ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_BANK_ACCOUNT FOREIGN KEY (bank_account_id) REFERENCES bank_account (id);

-- changeset ldf:1720984979297-14
ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES transaction_categories (id);

